# Replace bento grid section by line numbers (206-352 inclusive, 1-indexed)
filepath = r'e:\Saukhyam\saukhyam-website\src\app\page.tsx'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

print(f"Total lines before: {len(lines)}")


new_section_lines = [
    '      {/* \u2500\u2500 Amma & Programs \u2014 Next-Gen Bento Grid \u2500\u2500 */}\n',
    '      <section className={styles.bentoSection}>\n',
    '        <div className={styles.bentoBlobA} aria-hidden="true" />\n',
    '        <div className={styles.bentoBlobB} aria-hidden="true" />\n',
    '\n',
    '        <div className="container">\n',
    '          <motion.div\n',
    '            className={styles.bentoHeader}\n',
    '            initial="hidden"\n',
    '            whileInView="visible"\n',
    '            viewport={{ once: true }}\n',
    '            variants={fadeInUp}\n',
    '          >\n',
    '            <span className={styles.bentoBadge}>\n',
    '              <Heart size={14} />\n',
    '              Our Foundation &amp; Programs\n',
    '            </span>\n',
    '            <h2 className={styles.bentoTitle}>\n',
    '              Compassion That Creates <span className={styles.bentoTitleAccent}>Change</span>\n',
    '            </h2>\n',
    '          </motion.div>\n',
    '\n',
    '          <motion.div\n',
    '            className={styles.bentoGrid}\n',
    '            initial="hidden"\n',
    '            whileInView="visible"\n',
    '            viewport={{ once: true }}\n',
    '            variants={staggerContainer}\n',
    '          >\n',
    '            {/* Amma \u2014 Large Photo Card (spans 2 rows) */}\n',
    '            <motion.div variants={fadeInUp} className={`${styles.bCard} ${styles.bAmma}`}>\n',
    '              <div className={styles.bAmmaPhoto}>\n',
    '                <img src="/amma.png" alt="Mata Amritanandamayi (Amma)" className={styles.bAmmaImg} loading="lazy" />\n',
    '              </div>\n',
    '              <div className={styles.bAmmaBody}>\n',
    '                <span className={styles.bAmmaTag}>Inspired by Amma</span>\n',
    '                <h3 className={styles.bAmmaName}>Mata Amritanandamayi</h3>\n',
    '                <p className={styles.bAmmaText}>\n',
    "                  Saukhyam was born from Amma&apos;s vision \u2014 safe, chemical-free menstrual care for every woman.\n",
    '                </p>\n',
    '                <div className={styles.bAmmaQuote}>\n',
    '                  <span className={styles.bAmmaQM}>&ldquo;</span>\n',
    '                  <p>When we take care of nature, nature takes care of us.</p>\n',
    '                </div>\n',
    '                <Link href="/about" className={styles.bAmmaLink}>\n',
    '                  Read Our Story <ArrowRight size={15} />\n',
    '                </Link>\n',
    '              </div>\n',
    '            </motion.div>\n',
    '\n',
    '            {/* HEAL Logo Card (small square) */}\n',
    '            <motion.a href="/programs/heal" variants={fadeInUp} className={`${styles.bCard} ${styles.bHealLogo}`}>\n',
    '              <img src="/HealLogo/HEAL logo RGB_Vertical.png" alt="HEAL" className={styles.bLogoImage} />\n',
    '            </motion.a>\n',
    '\n',
    '            {/* HEAL Info Card (wider) */}\n',
    '            <motion.a href="/programs/heal" variants={fadeInUp} className={`${styles.bCard} ${styles.bHealInfo}`}>\n',
    '              <p className={styles.bInfoSub}>Health, Environment &amp; Active Living</p>\n',
    '              <p className={styles.bInfoDesc}>\n',
    '                Supporting women with PCOS &amp; period disorders through holistic wellness and chemical-free care.\n',
    '              </p>\n',
    '              <div className={styles.bInfoMetrics}>\n',
    '                <div className={styles.bInfoMetric}>\n',
    '                  <span className={styles.bInfoNum}>85%</span>\n',
    '                  <span className={styles.bInfoLabel}>Pain Reduction</span>\n',
    '                </div>\n',
    '                <div className={styles.bInfoMetric}>\n',
    '                  <span className={styles.bInfoNum}>70%</span>\n',
    '                  <span className={styles.bInfoLabel}>PCOS Improvement</span>\n',
    '                </div>\n',
    '              </div>\n',
    '              <span className={styles.bInfoArrow}><ArrowRight size={16} /></span>\n',
    '            </motion.a>\n',
    '\n',
    '            {/* REACH Info Card (wider, flipped position) */}\n',
    '            <motion.a href="/programs/reach" variants={fadeInUp} className={`${styles.bCard} ${styles.bReachInfo}`}>\n',
    '              <p className={styles.bInfoSub}>Rural Empowerment &amp; Community Health</p>\n',
    '              <p className={styles.bInfoDesc}>\n',
    '                Bringing chemical-free menstrual hygiene to rural India through satellite centres and local manufacturing.\n',
    '              </p>\n',
    '              <div className={styles.bInfoMetrics}>\n',
    '                <div className={styles.bInfoMetric}>\n',
    '                  <span className={styles.bInfoNum}>101</span>\n',
    '                  <span className={styles.bInfoLabel}>Villages</span>\n',
    '                </div>\n',
    '                <div className={styles.bInfoMetric}>\n',
    '                  <span className={styles.bInfoNum}>20+</span>\n',
    '                  <span className={styles.bInfoLabel}>States</span>\n',
    '                </div>\n',
    '              </div>\n',
    '              <span className={styles.bInfoArrow}><ArrowRight size={16} /></span>\n',
    '            </motion.a>\n',
    '\n',
    '            {/* REACH Logo Card (small square) */}\n',
    '            <motion.a href="/programs/reach" variants={fadeInUp} className={`${styles.bCard} ${styles.bReachLogo}`}>\n',
    '              <img src="/ReachLogo/HEAL logo RGB_Vertical.png" alt="REACH" className={styles.bLogoImage} />\n',
    '            </motion.a>\n',
    '\n',
    '            {/* CARE Logo Card (small square) */}\n',
    '            <motion.a href="/programs/care" variants={fadeInUp} className={`${styles.bCard} ${styles.bCareLogo}`}>\n',
    '              <img src="/CareLogo/CARE logo_Vertical.png" alt="CARE" className={styles.bLogoImage} />\n',
    '            </motion.a>\n',
    '\n',
    '            {/* CARE Info Card (wider) */}\n',
    '            <motion.a href="/programs/care" variants={fadeInUp} className={`${styles.bCard} ${styles.bCareInfo}`}>\n',
    '              <p className={styles.bInfoSub}>Campus Action for Reusable Essentials</p>\n',
    '              <p className={styles.bInfoDesc}>\n',
    '                Empowering campuses to shift toward sustainable menstrual choices through workshops and ambassador programs.\n',
    '              </p>\n',
    '              <div className={styles.bInfoMetrics}>\n',
    '                <div className={styles.bInfoMetric}>\n',
    '                  <span className={styles.bInfoNum}>50+</span>\n',
    '                  <span className={styles.bInfoLabel}>Campuses</span>\n',
    '                </div>\n',
    '                <div className={styles.bInfoMetric}>\n',
    '                  <span className={styles.bInfoNum}>10K+</span>\n',
    '                  <span className={styles.bInfoLabel}>Students</span>\n',
    '                </div>\n',
    '              </div>\n',
    '              <span className={styles.bInfoArrow}><ArrowRight size={16} /></span>\n',
    '            </motion.a>\n',
    '\n',
    '            {/* Impact Stats Card */}\n',
    '            <motion.div variants={fadeInUp} className={`${styles.bCard} ${styles.bStats}`}>\n',
    '              <span className={styles.bStatsNum}>5L+</span>\n',
    '              <span className={styles.bStatsLabel}>Women Empowered</span>\n',
    '            </motion.div>\n',
    '          </motion.div>\n',
    '        </div>\n',
    '      </section>\n',
]

# Replace lines 206-352 (0-indexed: 205-351)
new_lines = lines[:205] + new_section_lines + lines[352:]

print(f"Total lines after: {len(new_lines)}")

with open(filepath, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Done!")
