/** Auto-generated by scripts/sync-blog-images.mjs — do not hand-edit paths */

export type BlogImageAsset = { path: string; alt: string };

export const BLOG_IMAGE_POOL: Record<string, BlogImageAsset> = {
  /* ── Numbered pool — alt text is specific to the post each image is paired with ── */

  /* li-3 cover  — community women and children at a Saukhyam REACH distribution event */
  'img-000': { path: '/images/blog/img-000.jpg', alt: 'Musahar community women, girls, and children in Bihar — one of India\'s most marginalised Dalit communities, reached through Saukhyam\'s menstrual health intervention with SBI Foundation' },

  /* li-24 cover — a girl writing in a notebook (school and education context) */
  'img-001': { path: '/images/blog/img-001.jpg', alt: 'A girl writing in a notebook — menstrual health barriers contribute to school dropout among adolescent girls in India' },

  /* li-24 inline — children studying at an outdoor community school */
  'img-002': { path: '/images/blog/img-002.jpg', alt: 'Children studying at an outdoor community school — menstrual health is key to keeping girls enrolled' },

  /* li-9 cover  — Saukhyam field team walking alongside community women (trust in action) */
  'img-003': { path: '/images/blog/img-003.jpg', alt: 'Saukhyam field team walking alongside community women in Maharashtra — the trusted grassroots outreach that helped Rajasthani Mahila Mandal reach 2,000 women' },

  /* li-3 inline — girls at a rural community gathering, REACH beneficiaries */
  'img-004': { path: '/images/blog/img-004.jpg', alt: 'Young girls at a rural community gathering — Saukhyam REACH programme beneficiaries in Maharashtra receiving reusable pad kits' },

  /* li-21 cover — child at a hand pump, rural poverty context */
  'img-005': { path: '/images/blog/img-005.jpg', alt: 'Child pumping water in a flood-prone rural settlement — extreme poverty that Saukhyam flood relief kit drives serve in Assam' },

  /* li-13 cover — two young tribal girls smiling */
  'img-006': { path: '/images/blog/img-006.jpg', alt: 'Two young tribal girls smiling in Jharkhand — beneficiaries of Saukhyam\'s REACH menstrual health programme' },

  /* li-13 inline — women gathered in a Jharkhand village */
  'img-007': { path: '/images/blog/img-007.jpg', alt: 'Women sitting together in a Jharkhand village before a Saukhyam REACH reusable pad distribution session' },

  /* li-17 cover — rural woman cooking in extreme poverty, Northeast India */
  'img-008': { path: '/images/blog/img-008.jpg', alt: 'A woman cooking on an open fire in a remote Northeast India community — the daily reality REACH addresses in Assam and Meghalaya' },

  /* li-15 cover — woman making a clay stove in a sandy rural Rajasthan setting */
  'img-009': { path: '/images/blog/img-009.jpg', alt: 'A woman making a clay stove in a sandy Rajasthan village — the remote desert communities Saukhyam REACH reaches' },

  /* li-16 cover — girl cradling a newborn in a village */
  'img-010': { path: '/images/blog/img-010.jpg', alt: 'A young girl cradling a newborn in a village — the everyday lives that inspired founder Anju Bist to start Saukhyam Foundation' },

  /* li-16 inline — rural family in village, origin-story context */
  'img-011': { path: '/images/blog/img-011.jpg', alt: 'A rural family in a village — the community that Anju Bist grew up serving and that inspired Saukhyam\'s founding mission' },

  /* li-12 cover — woman with baby in a remote Northeast community */
  'img-012': { path: '/images/blog/img-012.jpg', alt: 'A woman from a remote community with her baby — HEAL satellite centre participants in Northeast India' },

  /* li-20 cover — Saukhyam + Amrita Serve team at a village temple */
  'img-013': { path: '/images/blog/img-013.jpg', alt: 'Saukhyam Foundation team with Amrita Serve volunteers and village community at a rural temple — Odisha REACH outreach' },

  /* li-19 cover — Saukhyam promotional poster: two women with reusable pad */
  'img-014': { path: '/images/blog/img-014.jpg', alt: 'Saukhyam reusable pad promotional image — two women of different generations choosing sustainable menstrual care' },

  /* li-22 cover  — indoor Saukhyam session: students being educated on reusable pads */
  'img-015': { path: '/images/blog/img-015.jpg', alt: 'Indoor Saukhyam Foundation awareness session with young women — the kind of campus education drive where medical college students first learn to choose reusables' },

  /* li-25 cover — Saukhyam team meeting with state government officials */
  'img-016': { path: '/images/blog/img-016.jpg', alt: 'Saukhyam Foundation team with state government officials during HEAL programme coordination meeting' },

  /* li-18 cover — Saukhyam team with gram panchayat officials */
  'img-017': { path: '/images/blog/img-017.jpg', alt: 'Saukhyam Foundation team and gram panchayat officials at a menstrual health partnership meeting' },

  /* li-18 inline — MoU signing (23/03/2026) */
  'img-018': { path: '/images/blog/img-018.jpg', alt: 'MoU document being signed between Saukhyam Foundation and village panchayat (23 March 2026)' },

  /* li-31 cover — Saukhyam hoarding at Kumbh Mela */
  'img-019': { path: '/images/blog/img-019.jpg', alt: 'Saukhyam Foundation billboard at Kumbh Mela — large-scale public outreach on reusable pad awareness and menstrual dignity' },

  /* (freed — previously li-22 cover; now reassigned — Rotary Shreyas Award stage) */
  'img-020': { path: '/images/blog/img-020.jpg', alt: 'Rotary Shreyas Award presentation ceremony — Anju Bist, Managing Director of Saukhyam Foundation, receiving the award on stage' },

  /* li-32 cover — large Rotary conference auditorium */
  'img-021': { path: '/images/blog/img-021.jpg', alt: 'Packed conference auditorium at Rotary International District 3080 — representing a decade of Saukhyam\'s large-scale advocacy' },

  /* li-23 cover — Anju Bist receiving award on stage */
  'img-022': { path: '/images/blog/img-022.jpg', alt: 'Anju Bist receiving the Rotary Shreyas Award on stage — institutional recognition that mirrors NIT Trichy CARE campus launch' },

  /* li-23 inline — Anju Bist at Rotary podium, Haridwar */
  'img-023': { path: '/images/blog/img-023.jpg', alt: 'Anju Bist speaking at Rotary District 3080 podium in Haridwar — campus-level institutional engagement' },

  /* li-4 inline  — Rotary Shreyas Award trophy close-up */
  'img-024': { path: '/images/blog/img-024.jpg', alt: 'Rotary Shreyas Award 2025-26 trophy — presented to Ms Anju Bist, Managing Director Saukhyam Foundation, for exemplary contribution to women\'s health' },

  /* li-27 cover — officials presenting recognition on a formal stage */
  'img-025': { path: '/images/blog/img-025.jpg', alt: 'Officials presenting formal recognition to Anju Bist on stage — institutional acknowledgement at par with NITI Aayog recognition' },

  /* li-27 inline — Anju Bist on stage, institutional ceremony */
  'img-026': { path: '/images/blog/img-026.jpg', alt: 'Anju Bist on stage at a national institutional recognition ceremony — Saukhyam Foundation receiving formal award' },

  /* li-32 inline — Rotary conference audience */
  'img-027': { path: '/images/blog/img-027.jpg', alt: 'Rotary International District 3080 conference audience — a gathering of the scale Saukhyam has touched over ten years' },

  /* li-26 cover — Rotary District Conference venue entrance, Haridwar */
  'img-028': { path: '/images/blog/img-028.jpg', alt: 'Rotary District Conference venue entrance at BHEL Convention Center, Haridwar — representing formal institutional cooperative partnerships' },

  /* li-14 cover — large institutional conference audience */
  'img-029': { path: '/images/blog/img-029.jpg', alt: 'Large institutional audience at a formal conference — the scale of student engagement Saukhyam CARE achieves at campuses like IIT' },

  /* li-5 cover  — large group at campus CARE event with Saukhyam bags */
  'img-030': { path: '/images/blog/img-030.jpg', alt: 'Large group photo at Azim Premji University Earth Day CARE event — students holding Saukhyam reusable pad kits' },

  /* li-5 inline  — group photo at indoor CARE session */
  'img-031': { path: '/images/blog/img-031.jpg', alt: 'Group photo at indoor Saukhyam CARE session at Azim Premji University with Saukhyam presentation on screen' },

  /* li-6 inline  — Anju Bist at Nexus Elante podium with Amma quote */
  'img-032': { path: '/images/blog/img-032.jpg', alt: 'Anju Bist speaking at Chandigarh CARE launch — Nexus Elante Mall event with Sri Mata Amritanandamayi Devi quote on screen' },

  /* li-10 cover  — large student audience at indoor CARE campus session */
  'img-033': { path: '/images/blog/img-033.jpg', alt: 'Large student audience at an indoor Saukhyam CARE campus session — the type of engagement at TISS Mumbai and similar institutions' },

  /* li-10 inline — multi-speaker panel at a campus Women's Day social event */
  'img-034': { path: '/images/blog/img-034.jpg', alt: 'Multi-speaker panel at a campus Women\'s Day social event — the type of collaborative CARE session Saukhyam runs at TISS Mumbai and similar institutions' },

  /* li-11 cover  — Anju Bist on bench in quiet conversation */
  'img-035': { path: '/images/blog/img-035.jpg', alt: 'Anju Bist in quiet conversation with a child — the personal, intimate care that defines Saukhyam\'s approach to HEAL journeys' },

  /* (unused by live posts — Period Society advocacy graphic) */
  'img-036': { path: '/images/blog/img-036.jpg', alt: 'The Period Society — "Are We Normalising Girls\' Suffering?" advocacy graphic shared by Saukhyam Foundation' },

  /* li-13 cover  — CARE Awards 2026 at "Happyness for HER" event: group of women recipients holding certificates and awards at Nexus Esplanade, KIIT University */
  'care-kiit-cover': { path: '/images/blog/care-kiit-cover.png', alt: 'Group of women and changemakers at the Happyness for HER CARE Awards 2026 ceremony — recognising youth menstrual health and sustainability advocates including Women Ambassadors from KIIT University' },

  /* li-1 cover — HEAL Launch at Nexus Esplanade Mall, Bhubaneshwar: Bhubaneshwar Mayor Sulochana Das and Saukhyam team lighting the ceremonial diya under the Happyness for HER banner */
  'li-1-heal-bhubaneshwar': { path: '/images/blog/li-1-heal-bhubaneshwar.png', alt: 'Inauguration of the HEAL programme launch at Nexus Esplanade Mall, Bhubaneshwar — Mayor Sulochana Das and Saukhyam team lighting the ceremonial diya at the Happyness for HER event' },

  /* li-14 cover — Rajasthani Mahila Mandal indoor awareness session: two women demonstrating Saukhyam reusable pads with Amma quote on screen */
  'li-14-rmm-session': { path: '/images/blog/li-14-rmm-session.png', alt: 'Awareness session at Jyoti Rajasthani Mahila Mandal, Mumbai — facilitators demonstrating Saukhyam reusable pad sets to community women' },

  /* li-15 cover — Students at a campus brainstorming session with a mind-map poster, engaged in CARE programme planning */
  'li-15-campus-brainstorm': { path: '/images/blog/li-15-campus-brainstorm.png', alt: 'Students gathered around a brainstorming poster at a campus CARE session — young people mapping out how to promote reusable menstrual products on their campus' },

  /* li-16 cover — Large group of Saukhyam women participants with Amma\'s portrait as backdrop at Amritapuri, making peace signs */
  'li-16-amma-group': { path: '/images/blog/li-16-amma-group.png', alt: 'Large group of Saukhyam Foundation women participants and volunteers gathered in front of Amma\'s portrait at Amritapuri — celebrating community and purpose' },

  /* li-17 cover — Large auditorium hall packed with students watching a Saukhyam awareness presentation on screen */
  'li-17-reach-hall': { path: '/images/blog/li-17-reach-hall.png', alt: 'Packed auditorium hall during a Saukhyam REACH awareness session — students attentively watching a presentation on reusable menstrual health' },

  /* li-18 cover — International Women\'s Day 2026 SHE Awards: group of women holding trophies at an awards ceremony */
  'li-18-iwd-she-awards': { path: '/images/blog/li-18-iwd-she-awards.png', alt: 'Women holding awards at the International Women\'s Day 2026 SHE Awards ceremony — celebrating women-led social impact including menstrual health work' },

  /* li-19 cover — Three people standing in a store/showroom with banana fiber and natural products on shelves */
  'li-19-store-visit': { path: '/images/blog/li-19-store-visit.png', alt: 'Anju Bist and Saukhyam team members at a partner store showcasing banana fiber and sustainable menstrual products' },

  /* li-20 cover — Anju Bist speaking on stage at a national conference with her nameplate visible */
  'li-20-anju-conference': { path: '/images/blog/li-20-anju-conference.png', alt: 'Anju Bist (MS. ANJU BISHT) speaking on stage at a national conference on menstrual health — representing Saukhyam Foundation as a panelist' },

  /* li-21 cover — Malayalam magazine feature with large group photo of women with Amma */
  'li-21-magazine': { path: '/images/blog/li-21-magazine.png', alt: 'Malayalam magazine feature spread — large group of women gathered with Amma, Sri Mata Amritanandamayi Devi, representing Saukhyam\'s founding inspiration' },

  /* li-22 cover — "The Deshbhakt" YouTube interview/podcast featuring a conversation on social impact */
  'li-22-deshbhakt': { path: '/images/blog/li-22-deshbhakt.png', alt: 'Saukhyam Foundation featured on The Deshbhakt — a conversation on social entrepreneurship, menstrual health, and sustainable impact in India' },

  /* li-23 cover — Large group of women in a hall holding Saukhyam reusable pad packages after a REACH distribution session */
  'li-23-reach-distribution': { path: '/images/blog/li-23-reach-distribution.png', alt: 'Large group of women and staff holding Saukhyam reusable pad packages after a REACH distribution and awareness session — representing scaled community impact' },

  /* li-24 cover — Government officials at a formal ceremony holding documents/books, Telangana district government event */
  'li-24-govt-ceremony': { path: '/images/blog/li-24-govt-ceremony.png', alt: 'Government officials at a Telangana district government ceremony — formal recognition and documentation of Saukhyam Foundation\'s public health collaboration' },

  /* li-8 cover   — Supreme Court menstrual leave news graphic */
  'img-037': { path: '/images/blog/img-037.jpg', alt: 'Supreme Court on menstrual leave — news headline shared by Saukhyam Foundation in context of menstrual health policy and HEAL programme' },

  /* li-30 cover  — Hindi menstrual health rights awareness graphic */
  'img-038': { path: '/images/blog/img-038.jpg', alt: 'Hindi graphic on Supreme Court menstrual leave ruling — menstrual health rights awareness shared by Saukhyam for inclusive advocacy' },

  /* heal-program-story — cover */
  'img-054': { path: '/images/blog/img-054.jpg', alt: 'HEAL programme story — women sharing transformation journeys in reproductive and menstrual health' },

  /* banana-fiber-science — cover */
  'img-056': { path: '/images/blog/img-056.jpg', alt: 'Banana fibre science — processing banana plant stems into natural absorbent filling for Saukhyam pads' },

  /* healing-periods-naturally — cover */
  'img-057': { path: '/images/blog/img-057.jpg', alt: 'Healing periods naturally — HEAL programme facilitator with women exploring holistic menstrual health' },

  /* rural-women-empowerment — cover */
  'img-058': { path: '/images/blog/img-058.jpg', alt: 'Rural women empowerment through Saukhyam Foundation — health, self-reliance, and dignity in villages' },

  /* zero-waste-menstruation — cover */
  'img-059': { path: '/images/blog/img-059.jpg', alt: 'Zero waste menstruation session — women replacing disposable plastic pad waste with Saukhyam reusables' },

  /* teen-first-period-guide — cover */
  'img-060': { path: '/images/blog/img-060.jpg', alt: 'Teenage girls at Saukhyam Foundation first-period awareness session — menstrual hygiene education' },

  /* pcos-and-reusable-pads — cover */
  'img-061': { path: '/images/blog/img-061.jpg', alt: 'Women with PCOS sharing improved health outcomes after switching to Saukhyam reusable menstrual pads' },

  /* school-awareness-campaign — cover */
  'img-062': { path: '/images/blog/img-062.jpg', alt: 'Saukhyam school awareness campaign — adolescent girls learning about reusable menstrual hygiene products' },

  /* amrita-serve-villages — cover */
  'img-063': { path: '/images/blog/img-063.jpg', alt: 'Amrita Serve village distribution programme — Saukhyam partnership reaching rural women across states' },

  /* disposable-pad-environment-cost — cover */
  'img-064': { path: '/images/blog/img-064.jpg', alt: 'Environmental cost of disposable pads — Saukhyam demonstration on plastic menstrual waste and landfill impact' },

  /* washing-care-guide — cover */
  'img-065': { path: '/images/blog/img-065.jpg', alt: 'Saukhyam reusable pad washing and care demonstration session — new users learning maintenance routine' },

  /* satellite-centre-kerala — cover */
  'img-066': { path: '/images/blog/img-066.jpg', alt: 'Saukhyam satellite centre in Kerala — community health worker training for REACH distribution and HEAL facilitation' },

  /* ── Named images (post-specific photography) ── */
  'musaharCover':      { path: '/images/blog/musaharCover.jpg',      alt: 'Musahar community outreach in Bihar — Saukhyam Foundation' },
  'musaharCommunity':  { path: '/images/blog/musaharCommunity.jpg',  alt: 'Musahar girls and women receiving Saukhyam reusable pad sets in Bihar' },
  'kumbhCover':        { path: '/images/blog/kumbhCover.jpg',        alt: 'Saukhyam at Kumbh Mela — UPSRLM partnership launch on the banks of the Ganga' },
  'kumbhGathering':    { path: '/images/blog/kumbhGathering.jpg',    alt: 'Rural women gathering at Kumbh Mela to learn about reusable menstrual pads' },
  'kumbhMou':          { path: '/images/blog/kumbhMou.jpg',          alt: 'MoU signing ceremony between Saukhyam Foundation and Uttar Pradesh State Rural Livelihood Mission' },
  'kumbhWomen':        { path: '/images/blog/kumbhWomen.jpg',        alt: 'Women at Kumbh Mela choosing Saukhyam reusable pads for their families' },
  'shreyasCover':      { path: '/images/blog/shreyasCover.jpg',      alt: 'Anju Bist receiving the Shreyas Award from Rotary International District 3080 at Haridwar' },
  'chandigarhCover':   { path: '/images/blog/chandigarhCover.jpg',   alt: 'CARE programme launch at Chandigarh — Punjab University and Nexus Elante Mall' },
  'rethinkCover':      { path: '/images/blog/rethinkCover.jpg',      alt: 'Rethink Normal — questioning disposable pad chemicals and menstrual health in India' },
};

export const POST_BLOG_IMAGES: Record<string, { cover: string; inline: string | null }> = {
  /*
   * Every image here has been visually verified.
   * img-000…img-035 = real Saukhyam field / event photos.
   * Named images    = post-specific event photography.
   * img-036…img-038 = menstrual-health advocacy graphics shared by Saukhyam.
   * img-039 onwards = unrelated stock photos — NOT used for any live post.
   */

  /* ── li-1  HEAL Launch Bhubaneshwar — Nexus Esplanade Mall diya lighting ceremony ── */
  'li-1':  { cover: 'li-1-heal-bhubaneshwar', inline: null },

  /* ── li-25 Musahar community Bihar — SBI Foundation REACH distribution ── */
  'li-25': { cover: 'img-000', inline: null },

  /* ── li-2  Kumbh / UPSRLM partnership ── */
  'li-2':  { cover: 'kumbhCover',      inline: 'kumbhWomen' },


  /* ── li-14 Girls realize period problems are not normal — CARE campus
             cover: Rajasthani Mahila Mandal indoor session with facilitators showing pads  ── */
  'li-14': { cover: 'li-14-rmm-session',      inline: null },

  /* ── li-15 "Try Reusable Pads First" — personal switch story
             cover: students brainstorming CARE campaign on campus  ── */
  'li-15': { cover: 'li-15-campus-brainstorm', inline: null },

  /* ── li-16 Change in the Himalayas — corporate to purpose
             cover: large group of Saukhyam women with Amma portrait backdrop  ── */
  'li-16': { cover: 'li-16-amma-group',        inline: null },

  /* ── li-17 Naari Shakti — women supporting women, IWD 2026
             cover: packed auditorium hall during a Saukhyam awareness session  ── */
  'li-17': { cover: 'li-17-reach-hall',        inline: null },

  /* ── li-18 Dr. Smita Dube drives 40-70 km to villages
             cover: IWD 2026 SHE Awards — women holding trophies  ── */
  'li-18': { cover: 'li-18-iwd-she-awards',    inline: null },

  /* ── li-19 Maushis at Bharati Vidyapeeth Pune
             cover: Anju Bist and team at a partner store with banana fiber products  ── */
  'li-19': { cover: 'li-19-store-visit',       inline: null },

  /* ── li-20 Karnataka ₹61 crore menstrual cups — policy shift
             cover: Anju Bist speaking on stage at a national conference  ── */
  'li-20': { cover: 'li-20-anju-conference',   inline: null },

  /* ── li-21 Cervical Cancer Awareness and menstrual health
             cover: Malayalam magazine feature — women gathered with Amma  ── */
  'li-21': { cover: 'li-21-magazine',          inline: null },

  /* ── li-22 Climate action — schoolgirl's backpack solution
             cover: The Deshbhakt interview — Saukhyam on a national social impact platform  ── */
  'li-22': { cover: 'li-22-deshbhakt',         inline: null },

  /* ── li-23 "Real founders build narratives" — disposable vs reusable
             cover: large group holding Saukhyam packages after REACH distribution  ── */
  'li-23': { cover: 'li-23-reach-distribution', inline: null },

  /* ── li-24 CARE-A-THON — campus becomes a movement
             cover: Telangana government ceremony — formal recognition of Saukhyam partnership  ── */
  'li-24': { cover: 'li-24-govt-ceremony',     inline: null },

  /* ── Generated posts (slug-keyed, not currently displayed in blogPosts) ── */
  'banana-fiber-science':           { cover: 'img-056', inline: null },
  'healing-periods-naturally':      { cover: 'img-057', inline: null },
  'rural-women-empowerment':        { cover: 'img-058', inline: null },
  'zero-waste-menstruation':        { cover: 'img-059', inline: null },
  'teen-first-period-guide':        { cover: 'img-060', inline: null },
  'pcos-and-reusable-pads':         { cover: 'img-061', inline: null },
  'school-awareness-campaign':      { cover: 'img-062', inline: null },
  'amrita-serve-villages':          { cover: 'img-063', inline: null },
  'disposable-pad-environment-cost':{ cover: 'img-064', inline: null },
  'washing-care-guide':             { cover: 'img-065', inline: null },
  'satellite-centre-kerala':        { cover: 'img-066', inline: null },
  'heal-program-story':             { cover: 'img-054', inline: null },
  'sports-women-saukhyam':          { cover: 'img-036', inline: null },
  'menstrual-equity-india':         { cover: 'img-039', inline: null },
  'chemical-free-periods':          { cover: 'img-041', inline: null },
  'banana-plant-circular-economy':  { cover: 'img-042', inline: null },
  'pad-woman-anju-bist':            { cover: 'img-044', inline: null },
  'college-campus-switch':          { cover: 'img-045', inline: null },
  'postpartum-recovery-pads':       { cover: 'img-046', inline: null },
  'climate-action-periods':         { cover: 'img-047', inline: null },
  'five-lakh-women-milestone':      { cover: 'img-049', inline: null },
  'future-sustainable-hygiene':     { cover: 'img-050', inline: null },
};

export function getPostImageKeys(key: string): { cover: string; inline: string | null } | undefined {
  return POST_BLOG_IMAGES[key];
}

export function getBlogImageAsset(id: string): BlogImageAsset | undefined {
  return BLOG_IMAGE_POOL[id];
}

export function resolvePostImages(key: string): { cover: BlogImageAsset; inline: BlogImageAsset | null } | undefined {
  const keys = POST_BLOG_IMAGES[key];
  if (!keys) return undefined;
  const cover = BLOG_IMAGE_POOL[keys.cover];
  if (!cover) return undefined;
  const inline = keys.inline ? BLOG_IMAGE_POOL[keys.inline] : null;
  return { cover, inline };
}
